[package]
name = "iced-css"
description = "CSS support for iced lib"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
iced.workspace = true
iced-css-core.workspace = true
iced-css-macro.workspace = true

[dev-dependencies]
iced_test.workspace = true
